-- Seed 48 AlphaNode entries with unique names, categories, and prices under $1
INSERT INTO AlphaNode (id, name, category, description, price, reputation, icon, status, isPurchased, createdAt) VALUES
(lower(hex(randomblob(16))), 'Quantum Scanner', 'Technical', 'Scans quantum price anomalies in real time.', 0.25, 92, 'activity', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Neural Oracle', 'Sentiment', 'Predicts market sentiment using neural networks.', 0.45, 88, 'zap', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'On-Chain Watcher', 'On-Chain', 'Monitors whale and smart money movements.', 0.65, 80, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Flash Arbitrage', 'Technical', 'Detects arbitrage opportunities across DEXs.', 0.55, 85, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Social Pulse', 'Sentiment', 'Aggregates social media signals for crypto.', 0.35, 77, 'activity', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Macro News AI', 'News', 'Summarizes macroeconomic news for traders.', 0.15, 90, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Chainlink Sentinel', 'On-Chain', 'Tracks Chainlink oracle updates.', 0.22, 81, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'DeFi Pulse', 'Technical', 'Monitors DeFi protocol health.', 0.33, 79, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Sentiment Surge', 'Sentiment', 'Detects sudden sentiment shifts.', 0.29, 83, 'zap', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Whale Alert', 'On-Chain', 'Alerts on large wallet movements.', 0.41, 87, 'activity', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Trend Seeker', 'Technical', 'Finds emerging trading trends.', 0.38, 84, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'News Aggregator', 'News', 'Aggregates crypto news headlines.', 0.19, 78, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'AI Arbitrage', 'Technical', 'AI-driven arbitrage detection.', 0.49, 86, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Market Maker', 'Technical', 'Simulates market making strategies.', 0.27, 82, 'activity', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Fear & Greed Index', 'Sentiment', 'Tracks market fear and greed.', 0.21, 80, 'zap', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Stablecoin Monitor', 'On-Chain', 'Monitors stablecoin flows.', 0.36, 85, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Flash News', 'News', 'Instant news alerts.', 0.18, 89, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'DEX Volume Tracker', 'Technical', 'Tracks DEX trading volumes.', 0.32, 88, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'NFT Pulse', 'On-Chain', 'Monitors NFT market activity.', 0.44, 77, 'activity', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'AI News Curator', 'News', 'Curates news using AI.', 0.23, 91, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Yield Hunter', 'Technical', 'Finds best DeFi yields.', 0.28, 84, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Sentiment AI', 'Sentiment', 'AI-powered sentiment analysis.', 0.31, 90, 'zap', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'On-Chain Validator', 'On-Chain', 'Validates on-chain transactions.', 0.26, 83, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Macro Pulse', 'News', 'Macro news pulse for crypto.', 0.24, 88, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Flash Sentiment', 'Sentiment', 'Real-time sentiment flash.', 0.17, 86, 'zap', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'DEX Arbitrage', 'Technical', 'Finds DEX arbitrage opportunities.', 0.39, 85, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Whale Scanner', 'On-Chain', 'Scans for whale activity.', 0.42, 82, 'activity', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'AI Macro News', 'News', 'AI-generated macro news.', 0.16, 87, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Trend AI', 'Technical', 'AI trend detection.', 0.34, 89, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Sentiment Radar', 'Sentiment', 'Radar for market sentiment.', 0.22, 81, 'zap', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Stablecoin Alert', 'On-Chain', 'Alerts on stablecoin moves.', 0.37, 80, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'News Flash', 'News', 'Breaking crypto news.', 0.14, 90, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Volume AI', 'Technical', 'AI volume analysis.', 0.29, 88, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'NFT Watch', 'On-Chain', 'Watches NFT trends.', 0.43, 79, 'activity', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Curated News', 'News', 'Curated crypto news.', 0.13, 91, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Yield Pulse', 'Technical', 'Pulse on DeFi yields.', 0.21, 87, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'AI Sentiment', 'Sentiment', 'AI-driven sentiment feed.', 0.27, 89, 'zap', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Chain Validator', 'On-Chain', 'Validates chain data.', 0.25, 84, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Macro Curator', 'News', 'Curates macro news.', 0.12, 88, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Sentiment Flash', 'Sentiment', 'Flash sentiment updates.', 0.19, 86, 'zap', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'DEX Scanner', 'Technical', 'Scans DEXs for trends.', 0.35, 85, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Whale Pulse', 'On-Chain', 'Pulse on whale activity.', 0.31, 83, 'activity', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'AI News Flash', 'News', 'AI-powered news flash.', 0.11, 90, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Yield Scanner', 'Technical', 'Scans for yield opportunities.', 0.23, 88, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Sentiment Curator', 'Sentiment', 'Curates sentiment data.', 0.18, 87, 'zap', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Chain Pulse', 'On-Chain', 'Pulse on chain activity.', 0.28, 82, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Macro Watch', 'News', 'Watches macro news.', 0.15, 89, 'globe', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'Trend Scanner', 'Technical', 'Scans for trading trends.', 0.26, 86, 'bar-chart', 'active', 0, CURRENT_TIMESTAMP),
(lower(hex(randomblob(16))), 'NFT Curator', 'On-Chain', 'Curates NFT data.', 0.24, 81, 'activity', 'active', 0, CURRENT_TIMESTAMP);
